# -*- coding: utf-8 -*-
"""Lip_detector

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SONeZmOT0lAi6fBxSMgH8FS9P14A877c
"""

from google.colab import drive
drive.mount('/content/gdrive')

!pip install ultralytics
from ultralytics import YOLO

# Load a COCO-pretrained YOLOv3n model
model = YOLO("yolov5n.pt")

# Display model information (optional)
model.info()

# Train the model on the COCO8 example dataset for 100 epochs
results = model.train(data="/content/gdrive/My Drive/lips_detector/lips.yaml", epochs=100)

# Run inference with the YOLOv3n model on the 'bus.jpg' image
results = model("../data/s1/bbaf2n.mpg")

model.save("lip.pt")

import shutil
source = './runs'
destination = '/content/gdrive/MyDrive/lip_yolo_run'
shutil.copytree(source, destination)

